// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://tgbnvyhfwmwcshowfiub.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InRnYm52eWhmd213Y3Nob3dmaXViIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzI5NzMwMjgsImV4cCI6MjA4ODU0OTAyOH0.tlZZovBsykjY1XDiAMVZUQOjwl3QHBLMH_7sVh2KjrM";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});